@startuml
!pragma layout smetana
 title My diagram
	Class directory1.ClassA{	

		

	}
	Class directory1.ClassB{	
	-String word	
	+int n	

		
	+returnWord() String	
	+returnInt() void	

	}
	Class ClassC{	
	-String word	
	+int n	

		
	+returnWord() String	
	+returnInt() void	

	}
	Class ClassD{	
	-String word	
	+int n	

		
	+returnWord() String	
	+returnInt() void	

	}
	Class ClassE{	
	-String word	
	+int n	

		
	+returnWord() String	
	+returnInt() void	

	}
ClassC <|-[dashed]- ClassD
ClassD <|-- ClassE

@enduml